### PR TITLE
 Refactor Unix process handling

### PR DESCRIPTION
**Pull request by ipetkov**
* Refactor the logic into several smaller units to allow for better
independent testing which would be impossible end-to-end
* I'm planning on extending these types to also better support (and test!) a solution for #51 , but that will come in a separate PR

### CODE REVIEW

**Comment by ipetkov** [comment]
I noticed the mac builds are consistently failing even in other PRs. I was able to reproduce the issue by running with a single core (`cargo test -j1`). Will dig into this, could be that a dependency got updated which broke things

**Comment by ipetkov** [comment]
I think I've resolved the issue, this is now ready for review.

Turns out this was due to a fix in mio's HUP semantics, which broke (what was already a flaky) test. I've kept the test in for now, I anticipate with additional refactors the test will be replaced by something better.

r? @alexcrichton

**Comment by alexcrichton** [comment]
Is there perhaps a high-level description of the changes here? I can dig through the commits and diff but I'm a bit strapped for time these days :(

**Comment by ipetkov** [comment]
Apologies @alexcrichton, I should have written a more detailed description of the changes (even for a "straightforward" refactor). I'll do this from now on.

### Motivation

* Today we kill a child process if its handle is dropped, and we synchronously wait until the child is reaped (the assumption that a SIGKILL is uncatchable and we're only waiting for the kernel to execute the kill)
* According to #51 it is possible that a kill doesn't terminate the child immediately, so the synchronous wait may cause problems (which we want to eventually refactor)
* Not reaping the process is also bad due to using up pids (even if we call `.forget()` today that pid doesn't get reaped as well)
* Today's tests run real with real processes end-to-end, which makes it very difficult to even simulate misbehaving processes

### Changes
* This PR attempts to internally refactor logical components to allow more isolated testing.
	- Any newly added traits/types are internal only and not exposed by any APIs
	- Semantics are (mostly) unchanged for now
* Added a internal `{Wait, Kill}` traits as abstractions around `process::Child::{wait, kill}` (i.e. to allow unit testing with mocks)
* Added a `Reaper` type which orchestrates between polling a `Signal` and the child process
	- This type now encompasses the `poll_exit` logic which was done within our `Child` wrapper
* Optimized out the `reaped` flag
	- Previously we would maintain a flag whether the process was reaped and short circuit on it
	- The stdlib maintains a similar flag internally (which prevents sending kills or waits on the pid), so this has been omitted
* Turned on travis caching only for installed cargo binaries (i.e. optimize from having to rebuild cargo-tarpaulin each time, but don't blow up the cache with intermediate cargo artifacts)


### Future changes
* Eventually we'll add another intermediate process wrapper type which will queue up any unreaped processes into an orphan queue and ensure the cleanup happens

**Comment by alexcrichton** [comment]
Ah no worries! That all sounds pretty reasonable to me. I am not personally a huge fan of mocking/extra traits, but I don't really have the time to maintain this crate any more so it's up to you :)

**Comment by ipetkov** [comment]
Thanks for the feedback! Yeah, it's a balancing act on not over-indexing on the internal traits, but I think this will help with testability.

I'll rebase and merge this in once the CI passes

**Pull request merged**
