### PR TITLE
[WIP] Update to use `std::future`

### PR DESCRIPTION
**Pull request by afinch7**

### CODE REVIEW

**Comment by 95th** [comment]
This repo is being merged into tokio

**Comment by ipetkov** [comment]
> This repo is being merged into tokio

Yes, the progress is being tracked in tokio-rs/tokio#1319, but nothing has landed quite yet, so @afinch7 feel free to work on it here for the time being (since the CI actually works), but we'll probably end up needing to rebase on the tokio repo

**Comment by afinch7** [comment]
@ipetkov I see your merge got approved. I will rebase ontop of the tokio repo as soon as you get it merged.

**Comment by ipetkov** [comment]
@afinch7 thanks for starting the work on this! The `tokio-process` source has been merged; I'm going to close this PR, but please rebase your changes in the `tokio` repo!

You can tag me on the PR, and feel free to use tokio-rs/tokio#1319 for tracking the work (of course you don't need to do all the left over tasks in the same PR!)

**Pull request closed without merging**
